# Generated by Django 4.0.6 on 2022-11-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('événement', '0003_alter_event_support_contact'),
        ('contrat', '0002_alter_contrat_sales_contact'),
        ('authentification', '0003_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
