# Generated by Django 4.1.2 on 2022-11-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0001_initial'),
        ('événement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_status', models.CharField(choices=[('created', 'created'), ('in_progress', 'in_progress'), ('finished', 'finished')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contrat.contrat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='événement.eventstatus'),
            preserve_default=False,
        ),
    ]
