# Generated by Django 4.0.6 on 2022-11-05 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_alter_client_sales_contact'),
        ('événement', '0002_eventstatus_event_contrat_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='authentification.user'
            ),
        ),
    ]
